### ISSUE TITLE
No support for dokka 1+

### ISSUE THREAD

**Issue by frangipanes** [tynn-xyz/BuildSrc#1]
Dokka 1.4.0 was released in August 2020 with many improvements to the documentation engine (such as documentation for Java enum fields). Is there any chance this repo can support the later versions of dokka to take advantage of these improvements?

**Comment by tynn** [comment]
I still haven't figured out how this would be possible to achieve. I missing the part where I create documentation for specific source sets only. Do you know how to configure it?

**Comment by tynn** [comment]
@frangipanes I finally managed to implement the changes. I'll push the new versions and the updated code soon.
